# Generated by Django 3.0.6 on 2020-05-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование поставщика')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('price', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Цена за единицу товара')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'kg'), (2, 'lb'), (3, 'pcs')], verbose_name='Единица измерения')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Provider')),
            ],
        ),
    ]
