# Generated by Django 2.1.7 on 2019-04-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='firstname',
            field=models.CharField(max_length=64, null=True, verbose_name='name of user'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=128, verbose_name='surname of user'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(verbose_name='age'),
        ),
    ]
