# Generated by Django 2.1.7 on 2019-04-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190404_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='firstname',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='gender',
            field=models.SmallIntegerField(choices=[(-1, 'Не указан'), (0, 'Женский'), (1, 'Мужской')], default=-1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=128, verbose_name='Фамилия'),
        ),
    ]
