# Generated by Django 2.2 on 2019-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190429_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='activation_key',
            field=models.CharField(max_length=128),
        ),
    ]
