# Generated by Django 2.2 on 2019-04-29 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20190429_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='email'),
        ),
    ]
