# Generated by Django 2.2 on 2019-05-01 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20190429_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserExtended',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tags', models.CharField(blank=True, max_length=128, verbose_name='Теги')),
                ('about', models.CharField(blank=True, max_length=128, verbose_name='О себе')),
            ],
        ),
    ]
