# Generated by Django 2.2 on 2019-05-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_shopuserextended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='shopuserextended',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='userpic', verbose_name='Аватар'),
        ),
    ]
