# Generated by Django 2.1.7 on 2019-03-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68, unique=True, verbose_name='name of category')),
                ('description', models.CharField(max_length=128, verbose_name='description of category')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68, verbose_name='name of product')),
                ('short_description', models.CharField(max_length=256, verbose_name='short comment of product')),
                ('full_description', models.TextField(blank=True, verbose_name='large protuct description')),
                ('image_preview', models.ImageField(blank=True, upload_to='product-img')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='product price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='stock quantity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
