# Generated by Django 2.1.7 on 2019-04-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=128, verbose_name='Адрес электронной почты')),
                ('subject', models.CharField(blank=True, max_length=64, null=True, verbose_name='Тема')),
                ('body', models.CharField(max_length=1024, verbose_name='Сообщение')),
            ],
        ),
    ]
