# Generated by Django 2.1.7 on 2019-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190330_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='overview',
            field=models.TextField(blank=True, verbose_name='large product review'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.CharField(max_length=512, verbose_name='short comment of product'),
        ),
    ]
