# Generated by Django 2.2 on 2019-04-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productandproperty',
            options={'verbose_name': 'Product and property (link)', 'verbose_name_plural': 'Products and properties (links)'},
        ),
    ]
