# Generated by Django 2.2 on 2019-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_products_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_preview',
            field=models.ImageField(default='product-img/blank-product.svg', upload_to='product-img'),
        ),
    ]
