# Generated by Django 2.2 on 2019-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190417_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_preview',
            field=models.ImageField(blank=True, default='product-img/blank-product.svg', upload_to='product-img'),
        ),
    ]
